name: 在IP段上运行Dirsearch # 工作流名称  
  
on:  
  workflow_dispatch: # 允许手动触发工作流  
    inputs:  
      ip_range:  
        description: '请输入CIDR表示法的IP段（例如：192.168.1.0/24）' # 输入描述  
        required: true # 此输入为必填项  
  
jobs:  
  dirsearch-ip-range: # 定义一个名为dirsearch-ip-range的作业  
    runs-on: ubuntu-latest # 作业运行在ubuntu-latest环境上  
    steps:  
      - name: 检出仓库 # 步骤名称：检出（下载）代码仓库  
        uses: actions/checkout@v3 # 使用GitHub提供的检出Action  
        with:  
          repository: maurosoria/dirsearch # 指定要检出的仓库  
          ref: main # 检出main分支  
          path: dirsearch # 将代码检出到当前工作目录下的dirsearch文件夹中  
  
      - name: 设置Python环境 # 步骤名称：设置Python运行环境  
        uses: actions/setup-python@v3 # 使用GitHub提供的设置Python环境的Action  
        with:  
          python-version: 3.8 # 指定Python版本为3.8  
  
      - name: 安装依赖 # 步骤名称：安装项目所需的依赖  
        working-directory: ./dirsearch # 在dirsearch目录下执行  
        run: | # 执行以下命令  
          python -m pip install --upgrade pip # 升级pip到最新版本  
          pip install -r requirements.txt # 安装项目所需的依赖库  
          pip install cidr # 安装cidr库，用于处理CIDR表示的IP段  
  
      - name: 生成IP列表 # 步骤名称：根据输入的CIDR生成IP地址列表  
        id: generate-ip-list # 为此步骤设置一个ID，以便后续步骤引用其输出  
        run: | # 执行以下命令生成IP列表  
          ip_range="${{ github.event.inputs.ip_range }}" # 获取用户输入的IP段  
          # 使用Python和cidr库生成IP段内的所有IP地址，并存储在ip_list变量中  
          ips=$(python -c "import cidr; print(' '.join(str(ip) for ip in cidr.IPRange(ip_range)))")  
          echo "::set-output name=ip_list::$ips" # 将生成的IP列表作为此步骤的输出  
  
      - name: 在IP段上运行Dirsearch # 步骤名称：对每个IP地址运行Dirsearch进行目录扫描  
        working-directory: ./dirsearch # 在dirsearch目录下执行  
        run: | # 执行以下命令进行扫描  
          ip_list="${{ steps.generate-ip-list.outputs.ip_list }}" # 获取上一步生成的IP列表  
          for ip in $ip_list; do # 遍历IP列表中的每个IP地址  
            echo "正在扫描 $ip..." # 输出正在扫描的IP地址信息  
            # 对每个IP地址运行Dirsearch进行扫描，使用随机User-Agent，设置请求延迟和重试次数  
            python3 dirsearch.py -u "http://$ip" -e * --random-agent --delay=10 --retries=3 || true  
          done  
  
      - name: 上传Dirsearch扫描结果 # 步骤名称：将扫描结果上传到构建产物中以便后续查看  
        uses: actions/upload-artifact@v3 # 使用GitHub提供的上传构建产物的Action  
        with:  
          name: dirsearch-results # 设置构建产物的名称为dirsearch-results  
          path: ./dirsearch/reports/*.txt # 指定要上传的文件路径，即扫描结果报告所在的路径
